### ISSUE TITLE
An origin story for Artificial Intelligence

### ISSUE THREAD

**Issue by apiad** [apiad/apiad#6]
https://github.com/apiad/apiad/blob/master/docs/podcast/what-is-ai.md

**Comment by svpino** [comment]
Awesome story! I do have a couple of comments:

1. First of all, nothing to say about the narrative. The story is really good. You definitely have to put it out there!
2. I'd consider the format to publish this story. I'm not sure your best bet is a podcast. I think it will work best as a blog post.
3. Podcasts are a medium that works a little bit better for unscripted conversations.
4. You also want to be relaxed with the format of the podcast. This is the only way you will be able to put an episode out there consistently. If you need a lot of preparation, it will be hard to keep episodes coming regularly.

That being said, none of these are fast rules, and you can literally do it however you like!

Good story!

**Comment by apiad** [comment]
Thanks, @svpino, for all the comments. I'm still figuring out the best format, so your points are very much on the spot. I will definitely publish this in written form, whether or not I decided to record it afterward. I want to experiment with the audio medium because I feel a lot more people are willing to give a few minutes to listen to something than reading it. Only testing will tell, I guess...

Thanks!

**Comment by mpcaples** [comment]
My observations are related to what Santiago has already said. 

1. I really like the article: it reads beautifully and has a great progression of information, as I am reading it... 
2. If I were listening to it, I am not sure I would be able to follow along quite as well. But that depends a lot on delivery, so I would say if you can present it as though you are telling a story rather than reading a script it might work just fine. 
3. Then 2 questions that go together: who is your target audience, and how long do you want the episode to be? I was able to follow the story well, but I'm already a little familiar with Turing and the Chinese Room experiment... I could see it might be a *lot* of information to someone who is not as familiar with the philosophical history that surrounds AI - and since you are possibly trying to give this background to this type of person, it might be a lot to take in. There are a few places where you use a term, and you do explain it, so that's good - but keeping all of those terms and history in one's head as a listener can be a bit challenging (depending on the person). 

I don't have any specific suggestions, I am sorry, but that was my impression as I read. I really enjoyed it a lot, and look forward to seeing/hearing where you go with this podcast! 

Also sorry, this is my first time commenting on github, so I am not sure if I did it the right way. :)

**Comment by apiad** [comment]
Thanks, @mpcaples, these are very good comments. On a second read, I'm also seeing that the language is somewhat heavy, and as you said, while one can re-read any part that we don't understand, listening is different, so I'm planning to simplify the language as much as I can.

Regarding the audience, I don't really know. I've been hearing some meta-podcasts and all of them say pretty much the same, do whatever you want to do, and let the audience form around you, not the other way around. So, despite it sounds somewhat egocentric, I think I'm gonna do just that, talk about whatever I feel interesting, and let's see who (if anyone) becomes interested.

Thanks again for your comments, and welcome to Github!
